package:
  name: 'mocalum'
  version: '0.1.0'

source:
  path: ../

build:
  number: 1
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  run:
    - xarray
    - netCDF4
    - matplotlib
    - jupyter
    - tqdm
    - pylint
    - python ==3.7.3
  host:
    - python
    - setuptools
test:
  imports:
    - mocalum