"""This module contains dictionaries of metadata information
related to MC_lum xarray datasets.
"""

# Dimensions metadata
DIMS = {}

basic_el = {'name':{'long_name':'',
                    'standard_name':'',
                    'units':'',
                    'URI':''}}

# Coordinates metadata
DIMS = {'x':{'long_name':'X coordinate',
             'standard_name':'x_coordinate',
             'units':'m',
             'URI':''},
        'y':{'long_name':'Y coordinate',
                'standard_name':'y_coordinate',
                'units':'m',
                'URI':''},
        'z':{'long_name':'Z coordinate',
                'standard_name':'z_coordinate',
                'alt_name': 'height_above_sea_level',
                'units':'m',
                'URI':''},
        'rng':{'long_name':'Range of measurements',
                 'standard_name':'range',
                 'units':'m',
                 'URI':''},
        'cc':{'long_name':'Correletation coefficient',
              'standard_name':'correlation_coefficient',
              'units':'',
              'URI':''},
        'wdir':{'long_name':'Wind direction',
                'standard_name':'wind_from_direction',
                'units':'degree',
                'URI':''},
        'sectrsz':{'long_name':'PPI sector size',
                   'standard_name':'scanned_sector_size',
                   'units':'degree',
                   'URI':''},
        'time':{'long_name':'Time',
                'standard_name':'time',
                'units':'s',
                'URI':''}
         }

VARS = {'ws':{'long_name':'Wind speed',
                 'standard_name':'wind_speed',
                 'units':'m.s-1',
                 'URI':''},
        'vrad':{'long_name':'Radial wind speed',
                'alt_name': 'LOS wind speed',
                'standard_name':'radial_velocity_of_scatterers_away_from_instrument',
                'units':'m.s-1',
                'URI':''},
        'x':{'long_name':'X coordinate',
                'standard_name':'x_coordinate',
                'units':'m',
                'URI':''},
        'y':{'long_name':'Y coordinate',
                'standard_name':'y_coordinate',
                'units':'m',
                'URI':''},
        'z':{'long_name':'Z coordinate',
                'standard_name':'z_coordinate',
                'alt_name': 'height_above_sea_level',
                'units':'m',
                'URI':''},
        'u':{'long_name':'Wind along X coordinate',
                'standard_name':'eastward_wind',
                'units':'m.s-1',
                'URI':''},
        'v':{'long_name':'Wind along Y coordinate',
                'standard_name':'northward_wind',
                'units':'m.s-1',
                'URI':''},
        'w':{'long_name':'Vertical wind speed',
                'standard_name':'upward_air_velocity',
                'units':'m.s-1',
                'URI':''},
        'az':{'long_name':'Azimuth angle',
                'standard_name':'azimuth_angle',
                'units':'degree',
                'URI':''},
        'el':{'long_name':'Elevation angle',
                'standard_name':'elevation_angle',
                'units':'degree',
                'URI':''},
        'rng':{'long_name':'Range',
                'standard_name':'range',
                'units':'m',
                'URI':''},
        'unc_az':{'long_name':'Azimuth uncertainty',
                'standard_name':'azimuth_uncertainty',
                'units':'degree',
                'URI':''},
        'unc_el':{'long_name':'Elevation uncertainty',
                'standard_name':'elevation_uncertainty',
                'units':'degree',
                'URI':''},
        'unc_rng':{'long_name':'Range uncertainty',
                'standard_name':'range_uncertainty',
                'units':'m',
                'URI':''},
        'unc_est':{'long_name':'Radial velocity estimation uncertainty',
                'standard_name':'los_estimation_uncertainty',
                'units':'m.s-1',
                'URI':''},
        'unc_ws':{'long_name':'Wind speed uncertainty',
                  'standard_name':'wind_speed_uncertainty',
                  'units':'m.s-1',
                  'URI':''},
        'unc_wdir':{'long_name':'Wind direction uncertainty',
                    'standard_name':'wind_direction_uncertainty',
                    'units':'degree',
                    'URI':''},
        'wdir':{'long_name':'Wind direction',
                'standard_name':'wind_from_direction',
                'units':'degree',
                'URI':''},
        'rng':{'long_name':'Range of measurements',
                 'standard_name':'range',
                 'units':'m',
                 'URI':''},
        'corr_coef':{'long_name':'Correlation coefficient',
              'standard_name':'correlation_coefficient',
              'units':'',
              'URI':''},
        'sectrsz':{'long_name':'PPI sector size',
                   'standard_name':'scanned_sector_size',
                   'units':'degree',
                   'URI':''},
        'no_scans':{'long_name':'Number of scans in measurement scenario',
                   'standard_name':'number_of_scans',
                   'units':'',
                   'URI':''},
        'no_los':{'long_name':'Number of line-of-sights per scan',
                   'standard_name':'number_of_los',
                   'units':'',
                   'URI':''},
        'scan_tm':{'long_name':'Time to complete one scan',
                   'standard_name':'scan_time',
                   'units':'s',
                   'URI':''},
        'return_tm':{'long_name':'Time to return to start of scan',
                   'standard_name':'return_to_start_time',
                   'units':'s',
                   'URI':''},
        'lidar_pos_x':{'long_name':'Lidar X coordiante',
                   'standard_name':'lidar_x_coordinate',
                   'units':'m',
                   'URI':''},
        'lidar_pos_y':{'long_name':'Lidar Y coordiante',
                   'standard_name':'lidar_y_coordinate',
                   'units':'m',
                   'URI':''},
        'lidar_pos_z':{'long_name':'Lidar Z coordiante',
                   'standard_name':'lidar_z_coordinate',
                   'alt_name': 'lidar_height_above_sea_level',
                   'units':'m',
                   'URI':''}

         }